### PR TITLE
Disable sourcemap breaking mobx builds

### PR DESCRIPTION
**Pull request by soyarsauce**
Can revert when we trace down root cause

### CODE REVIEW

**Comment by kring** [comment]
Is it a sourcemap/CSS related error in release builds only? I recently ran into that and was able to fix/work around it after a bunch of futzing. Here's my full project:
https://github.com/TerriaJS/TerriaMap/compare/mobx...kring:ogc3d

I think it was specifically removing `import Variables from "../Styles/variables.scss";` from render.jsx that did the trick.

**Comment by steve9164** [comment]
I was able to fix the problem by changing:
```
'resolve-url-loader?sourceMap',   
```
to
```
{                                                                                                                                                                                                                                                                                           
  loader: 'resolve-url-loader',                                                                                                                                                                                                                                                             
  options: {                                                                                                                                                                                                                                                                                
    sourceMap: false                                                                                                                                                                                                                                                                        
  }                                                                                                                                                                                                                                                                                         
},
```
in the couple of places that `resolve-url-loader` is used in the TerriaMap build config (specifically in my case for Terria-PacificMap)

**Comment by kring** [comment]
Interesting, I had tried removing all the `?sourceMap` bits, but hadn't considered that sourcemaps might default to true.

**Comment by steve9164** [comment]
Closing in favour of fixes in #459 which avoids changing sourcemaps settings in prod. Style sourcemaps seem to still work too.

Maybe some of the babel plugin changes here should be replicated in another PR?

**Pull request closed without merging**
