### PR TITLE
Provide lots of guidance for people wanting to skin/re-theme TerriaMap.

### PR DESCRIPTION
**Pull request by stevage**

### CODE REVIEW

**Comment by AlexGilleran** [comment]
:+1:

**Comment by rdengate** [comment]
This is awesome! One of the things AREMI and GEOGLAM change is the colour of the progress bar... is that something that could be added to global.scss?

**Comment by stevage** [comment]
Which progress bar? The one at the top?

Also, should have made explicit, that I think some of the stuff in global.scss should be made standard, like using $color-primary and $font-base etc absolutely everywhere. But I'll leave that to @AlexGilleran to migrate over whenever convenient.

**Comment by rdengate** [comment]
> Which progress bar? The one at the top?

Yep, that one.

**Pull request merged**
